context.properties = {
    core.daemon = true
    core.name = niko-test
    default.clock.rate = 48000
}
context.spa-libs = { support.* = support/libspa-support audio.convert.* = audioconvert/libspa-audioconvert }
context.modules = [
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-spa-node-factory }
    { name = libpipewire-module-client-node }
    { name = libpipewire-module-adapter }
    { name = libpipewire-module-metadata }
    { name = libpipewire-module-access }
]
context.objects = [
    { factory = metadata args = { metadata.name = default } }
    { factory = adapter args = { factory.name = support.null-audio-sink node.name = niko-test-sink media.class = Audio/Sink audio.position = [ FL FR ] } }
    { factory = adapter args = { factory.name = support.null-audio-sink node.name = niko-test-source media.class = Audio/Source audio.position = [ FL FR ] } }
    { factory = adapter args = { factory.name = support.null-audio-sink node.name = niko-test-stream media.class = Stream/Output/Audio audio.position = [ FL FR ] application.name = "Som ficticio" application.process.id = NIKO_FIXTURE_PID } }
]
