// Templates ASCII de cabeça e cabelo (puros). Grade de 14 colunas: a coluna c vira x = c + 5 no
// sprite do personagem e a linha r vira y = r + 3 (em pé). A cabeça ocupa as colunas 1..12 e as
// linhas 4..14; orelhas nas colunas 0 e 13 (linhas 10–11) de frente/costas e na coluna 8 de perfil.
//
// Legenda do cabelo: o = base, h = claro, H = brilho, d = sombra, D = sombra profunda,
// z = raspado (cabelo misturado à pele), k = brilho da pele (careca), a = acessório (elástico).
// Legenda da cabeça: s = pele, S = pele em sombra, L = pele clara, e/E = olho (topo/base),
// b = blush, m = boca, r = interior da orelha.
import type { HairStyle } from '../api';

export interface Tpl {
  /** Deslocamento em colunas da grade (pode ser negativo para volumes largos). */
  x: number;
  /** Linha inicial na grade. */
  y: number;
  rows: readonly string[];
}

/** Camadas de um penteado numa direção: `back` vai atrás do corpo; `front` por cima da cabeça. */
export interface HairLayers {
  front?: Tpl;
  back?: Tpl;
}

export type HeadView = 'down' | 'up' | 'side';

const t = (x: number, y: number, rows: readonly string[]): Tpl => ({ x, y, rows });

export const HEAD_BASE: Readonly<Record<HeadView, Tpl>> = {
  down: t(0, 4, [
    '...ssssssss...',
    '..ssssssssss..',
    '.sssssssssssS.',
    '.sssssssssssS.',
    '.sssssssssssS.',
    '.sssssssssssS.',
    'ssssessssessSs',
    'SsssEssssEssSS',
    '.ssbssssssbsS.',
    '..ssssmmsssS..',
    '...sssssssS...',
  ]),
  up: t(0, 4, [
    '...ssssssss...',
    '..ssssssssss..',
    '.sssssssssssS.',
    '.sssssssssssS.',
    '.sssssssssssS.',
    '.sssssssssssS.',
    'ssssssssssssSs',
    'SssssssssssSSS',
    '.sssssssssssS.',
    '..ssssssssSS..',
    '...sssssssS...',
  ]),
  side: t(0, 4, [
    '...ssssssss...',
    '..ssssssssss..',
    '.sssssssssssS.',
    '.sssssssssssS.',
    '.sssssssssssS.',
    '.sssssssssssS.',
    '.sseSssssrsSS.',
    'sssEsssssrsSS.',
    '.sssbsssssSS..',
    '.smssssssSS...',
    '..sssssssS....',
  ]),
};

/** Penteados por direção. 'side' é desenhado virado para a esquerda (direita = espelho). */
export const HAIR: Readonly<Record<HairStyle, Readonly<Record<HeadView, HairLayers>>>> = {
  short: {
    down: {
      front: t(0, 2, [
        '....oooooo....',
        '..ooohhhhooo..',
        '.oohhHHhhoood.',
        'oohhhhhhoooodd',
        'ohhooooooooddd',
        'oooooooo...odd',
        'ood.d.......dd',
        'od..........dd',
      ]),
    },
    up: {
      front: t(0, 2, [
        '....oooooo....',
        '..ooohhhhooo..',
        '.oohhHHhhoood.',
        'oohhhhhhoooodd',
        'ohhooooooooddd',
        'oooooooooooodd',
        'oooooooooooodd',
        'oooooooooooddd',
        '.oooooooooodd.',
        '.dooooooooodd.',
        '..ddoooooddd..',
        '....dddddd....',
      ]),
    },
    side: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'oohhhhhhoooodd',
        'oooooohooooodd',
        '.o.o.ooooooodd',
        '.......oooodd.',
        '.......ooooddd',
        '.......d.oodd.',
        '.........oddd.',
        '..........dd..',
      ]),
    },
  },
  buzz: {
    down: {
      front: t(0, 3, [
        '...oooooooo...',
        '..ohhhhooood..',
        '.ohhooooooood.',
        '.oooooooooood.',
        '.od........do.',
        '.d..........d.',
      ]),
    },
    up: {
      front: t(0, 3, [
        '...oooooooo...',
        '..ohhhhooood..',
        '.ohhooooooood.',
        '.oooooooooood.',
        '.oooooooooood.',
        '.oooooooooodd.',
        '.oooooooooodd.',
        '.dooooooooodd.',
        '..dooooooodd..',
        '...dddddddd...',
      ]),
    },
    side: {
      front: t(0, 3, [
        '...oooooooo...',
        '..ohhhhooood..',
        '.ohhooooooood.',
        '.oooooooooood.',
        '....oooooood..',
        '.......ooood..',
        '.......d.ood..',
        '.........od...',
        '.........dd...',
      ]),
    },
  },
  spiky: {
    down: {
      front: t(0, 0, [
        '...o...o..o...',
        '..oo..oho.oo..',
        '.ooohhhhhoood.',
        '.ohhHHhhooood.',
        'oohhhhhooooodd',
        'ohhooooooooodd',
        'oooo.ooo.oo.dd',
        'oo.o..o.....dd',
        'od..........dd',
        '.d..........d.',
      ]),
    },
    up: {
      front: t(0, 0, [
        '...o...o..o...',
        '..oo..oho.oo..',
        '.ooohhhhhoood.',
        '.ohhHHhhooood.',
        'oohhhhhooooodd',
        'ohhooooooooodd',
        'oooooooooooodd',
        'oooooooooooodd',
        'oooooooooooddd',
        '.oooooooooodd.',
        '.dooooooooodd.',
        '..ddoooooddd..',
        '....dddddd....',
      ]),
    },
    side: {
      front: t(0, 0, [
        '.......o...o..',
        '....oo.oo.oo..',
        '..ooohhhhooo..',
        '.ohhHHhhhoood.',
        'oohhhhhhoooodd',
        'oooooohooooodd',
        'oo.o.ooooooodd',
        '.......oooodd.',
        '.......ooooddd',
        '.......d.oodd.',
        '.........oddd.',
        '..........dd..',
      ]),
    },
  },
  side_part: {
    down: {
      front: t(0, 2, [
        '....oooooo....',
        '..ooDhhhhooo..',
        '.ooDhHHhhhood.',
        'oooDhhhhhhoodd',
        'ooo.oooooooddd',
        'oo....oooooodd',
        'od.......oo.dd',
        'od..........dd',
      ]),
    },
    up: {
      front: t(0, 2, [
        '....oooooo....',
        '..ooDhhhhooo..',
        '.ooDhHHhhhood.',
        'oooDhhhhhhoodd',
        'oooDoooooooddd',
        'oooooooooooodd',
        'oooooooooooodd',
        'oooooooooooddd',
        '.oooooooooodd.',
        '.dooooooooodd.',
        '..ddoooooddd..',
        '....dddddd....',
      ]),
    },
    side: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'oohhhhhhoooodd',
        'ohhhooooooodd.',
        'oo.ooooooooodd',
        'o......oooodd.',
        '.......ooooddd',
        '.......d.oodd.',
        '.........oddd.',
        '..........dd..',
      ]),
    },
  },
  curly: {
    down: {
      front: t(0, 1, [
        '....ohoooo....',
        '..ohoHohooho..',
        '.oHohhohohood.',
        'ohohoohooohodd',
        'oohoohoooohodd',
        'ohoodoohodoodd',
        'oodo.o..o.oodd',
        'odo........odd',
        'do..........dd',
      ]),
    },
    up: {
      front: t(0, 1, [
        '....ohoooo....',
        '..ohoHohooho..',
        '.oHohhohohood.',
        'ohohoohooohodd',
        'oohoohoooohodd',
        'ohoodoohodoodd',
        'oodoohoodoohdd',
        'odohoodohoodod',
        'ooodohooododdd',
        '.ohoodohoodod.',
        '.dodoohodoodd.',
        '..ddodooddd...',
        '....dddddd....',
      ]),
    },
    side: {
      front: t(0, 1, [
        '....ohoooo....',
        '..ohoHohooho..',
        '.oHohhohohood.',
        'ohohoohooohodd',
        'oohoohoooohodd',
        'odo.dooohodood',
        '.o.o..oodoohdd',
        '.......ohooddd',
        '.......doodod.',
        '........d.odd.',
        '.........oddd.',
        '..........dd..',
      ]),
    },
  },
  afro: {
    down: {
      front: t(-1, 0, [
        '....oohhhooo....',
        '..oohhHHhhoooo..',
        '.oohhHHhhhooooo.',
        'oohhhhhhoooooodd',
        'ohhhhooooooooodd',
        'ohhooooooooooodd',
        'oooooooooooooodd',
        'oooo........oodd',
        'ooo..........odd',
        'ood..........ddd',
        'od............dd',
        '.d............d.',
      ]),
    },
    up: {
      front: t(-1, 0, [
        '....oohhhooo....',
        '..oohhHHhhoooo..',
        '.oohhHHhhhooooo.',
        'oohhhhhhoooooodd',
        'ohhhhooooooooodd',
        'ohhooooooooooodd',
        'oooooooooooooodd',
        'oooooooooooooodd',
        'oooooooooooooddd',
        'oooooooooooooddd',
        '.oooooooooooodd.',
        '.ddooooooooddd..',
        '...ddddddddd....',
      ]),
    },
    side: {
      front: t(-1, 0, [
        '....oohhhooo....',
        '..oohhHHhhoooo..',
        '.oohhHHhhhooooo.',
        'oohhhhhhoooooodd',
        'ohhhoooooooooodd',
        'ohhooooooooooodd',
        'oooooooooooooodd',
        'oo...ooooooooodd',
        '........oooooddd',
        '........d.oooddd',
        '..........oooddd',
        '..........oddd..',
        '...........dd...',
      ]),
    },
  },
  bob: {
    down: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'ohhhhhhhoooodd',
        'ohhooooooooodd',
        'oooooooooooodd',
        'ooo........odd',
        'ood........odd',
        'od..........dd',
        'od..........dd',
        'od..........dd',
        'odd........ddd',
        '.dd........dd.',
      ]),
    },
    up: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'ohhhhhhhoooodd',
        'ohhooooooooodd',
        'oooooooooooodd',
        'oooooooooooodd',
        'oooooooooooodd',
        'oooooooooooddd',
        'oooooooooooddd',
        'oooooooooooddd',
        'odoooooooodddd',
        '.dddddddddddd.',
      ]),
    },
    side: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'oohhhhhhoooodd',
        'ohhooooooooood',
        'ooooooooooood.',
        'oo....oooooodd',
        'o.....oooooddd',
        '......ohoooddd',
        '......oooooddd',
        '......ooooodd.',
        '......dddoddd.',
        '.......ddddd..',
      ]),
    },
  },
  long: {
    down: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhhhhooo..',
        '.ohhHhDhhHood.',
        'ohhhhDDohhoodd',
        'ohhoo....ooodd',
        'oho........odd',
        'oho........odd',
        'oo..........dd',
        'oo..........dd',
        'oh..........dd',
        'oo..........dd',
        'oo..........dd',
        'oho........odd',
        'ooo........odd',
        'odd........ddd',
        '.dd........dd.',
      ]),
      back: t(-1, 8, [
        'oooooooooooooodd',
        'oooooooooooooodd',
        'oooooooooooooodd',
        'oooooooooooooodd',
        'oooooooooooooodd',
        'oooooooooooooodd',
        'oooooooooooooodd',
        'oooooooooooooodd',
        'dooooooooooooddd',
        'dddoooooooooddd.',
        '.dddddddddddd...',
      ]),
    },
    up: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'ohhhhhhhoooodd',
        'ohhooooooooodd',
        'oooooooooooodd',
        'ohoooooooooodd',
        'ohoooooooooodd',
        'oooooooooooddd',
        'oooooooooooddd',
        'ooohoooooooddd',
        'oooooooooooddd',
        'ooohooooooodd.',
        'oooooooooooddd',
        'odoooooooooddd',
        'oddooooooodddd',
        '.dddoooooddd..',
        '...dddddddd...',
      ]),
    },
    side: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'oohhhhhhoooodd',
        'ohhooooooooodd',
        'ooooooooooood.',
        'oo....oooooodd',
        'o.....ooooodd.',
        '......ohooodd.',
        '......oooooddd',
        '......ooohoddd',
        '.......oooodd.',
        '.......ooooddd',
        '.......ohooodd',
        '.......oooodd.',
        '.......ooood..',
        '........dddd..',
      ]),
    },
  },
  ponytail: {
    down: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'ohhhhhhhoooodd',
        'ohoooooooooodd',
        'oo..........dd',
        'od..........dd',
        '.d...........d',
      ]),
      back: t(12, 4, [
        '.aa',
        'ohd',
        'ohd',
        'ood',
        'ohd',
        '.od',
        '.od',
        '.od',
        '.dd',
        '..d',
      ]),
    },
    up: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'ohhhhhhhoooodd',
        'ohoooohooooddd',
        'ooooodaadooodd',
        'oooooohhoooodd',
        'ooooohoodooood',
        '.ooooohoddood.',
        '.dooooohodood.',
        '..ddooohodod..',
        '....ddohoddd..',
        '......ohod....',
        '......ohdd....',
        '......ood.....',
        '.......dd.....',
      ]),
    },
    side: {
      front: t(0, 2, [
        '....oooooo.....',
        '..oohhhhhoooo..',
        '.ohhHHhhhooaad.',
        'oohhhhhhoooohd.',
        'ohoooooooooohd.',
        'oo.ooooooooohd.',
        '.......ooood.od',
        '.......oood..od',
        '.......d.od..od',
        '.........dd..dd',
        '..............d',
      ]),
    },
  },
  bun: {
    down: {
      front: t(0, 0, [
        '.....oooo.....',
        '....ohHhod....',
        '...ooddddoo...',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'ohhhhhhhoooodd',
        'ohoooooooooodd',
        'oo..........dd',
        'od..........dd',
        '.d..........d.',
      ]),
    },
    up: {
      front: t(0, 0, [
        '.....oooo.....',
        '....ohHhod....',
        '...ooddddoo...',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'ohhhhhhhoooodd',
        'ohoooooooooodd',
        'oooooooooooodd',
        'oooooooooooodd',
        'oooooooooooddd',
        '.oooooooooodd.',
        '.dooooooooodd.',
        '..ddoooooddd..',
        '....dddddd....',
      ]),
    },
    side: {
      front: t(0, 0, [
        '.........ooo..',
        '........ohHod.',
        '....ooooodddd.',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'oohhhhhhoooodd',
        'ohoooooooooodd',
        'oo.ooooooooodd',
        '.......oooodd.',
        '.......ooooddd',
        '.......d.oodd.',
        '.........oddd.',
        '..........dd..',
      ]),
    },
  },
  pigtails: {
    down: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhDhhooo..',
        '.ohhHhDhHhood.',
        'ohhhhhDhhhoodd',
        'ohhooooooooodd',
        'ooo.o....o.odd',
        'od..........dd',
        'od..........dd',
      ]),
      back: t(-2, 8, [
        '.a..............a.',
        'oho............ohd',
        'ohd............ohd',
        'ohd............odd',
        'ood............odd',
        '.od............dd.',
        '.d..............d.',
      ]),
    },
    up: {
      front: t(-2, 2, [
        '......oooooo......',
        '....oohhDhhooo....',
        '...ohhHhDhHhood...',
        '..ohhhhhDhhhoodd..',
        '..ohhoooDooooodd..',
        '..ooooooDoooooddd.',
        '..ooooooDoooooodd.',
        '.aooooooDooooodda.',
        'ohooooooDoooooodhd',
        'ohd.ooooDooooo.ohd',
        'ohd..ddoDoodd..odd',
        'ood....dddd....odd',
        '.od............dd.',
        '.d..............d.',
      ]),
    },
    side: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'oohhhhhhoooodd',
        'ohhooooooooodd',
        'oo.o.ooooooodd',
        '.......oooodd.',
        '.......oooaad.',
        '.......d.oohd.',
        '.........ohdd.',
        '.........ohd..',
        '.........ood..',
        '.........odd..',
        '..........d...',
      ]),
    },
  },
  mohawk: {
    down: {
      front: t(0, 0, [
        '......oo......',
        '.....ohoo.....',
        '.....hHod.....',
        '...zzhhodzz...',
        '..zzzohodzzz..',
        '.zzzzoooodzzz.',
        '.zzzzoood.zzz.',
        '.z..........z.',
      ]),
    },
    up: {
      front: t(0, 0, [
        '......oo......',
        '.....ohoo.....',
        '.....hHod.....',
        '...zzhhodzz...',
        '..zzzohodzzz..',
        '.zzzzoooodzzz.',
        '.zzzzoooodzzz.',
        '.zzzzoooodzzz.',
        '.zzzzoooodzzz.',
        '.zzzzzoodzzzz.',
        '.zzzzzoodzzzz.',
        '..zzzzoddzzz..',
        '....zzddzz....',
      ]),
    },
    side: {
      front: t(0, 0, [
        '...ooo.o......',
        '..oohhoooo.o..',
        '..ohHHhhoooo..',
        '..zzzzzzzzodd.',
        '.zzzzzzzzzzzz.',
        '.zzzzzzzzzzzz.',
        '.......zzzzzz.',
        '........zzzzz.',
        '.......z.zzzz.',
        '.........zzz..',
      ]),
    },
  },
  bald: {
    down: {
      front: t(0, 4, [
        '..............',
        '....kk........',
        '...k..........',
        '..............',
        'zz..........zz',
        'zz..........zz',
      ]),
    },
    up: {
      front: t(0, 4, [
        '..............',
        '....kk........',
        '...k..........',
        '..............',
        '.zzzzzzzzzzzz.',
        'zzzzzzzzzzzzzz',
        '.zzzzzzzzzzzz.',
        '..zzzzzzzzzz..',
      ]),
    },
    side: {
      front: t(0, 4, [
        '..............',
        '....kk........',
        '...k..........',
        '..............',
        '.......zzzzzz.',
        '.......z.zzzz.',
        '.........zzz..',
      ]),
    },
  },
  wavy: {
    down: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'ohhhhhhhoooodd',
        'ohhooooooooddd',
        'oooooo....oodd',
        'ohd.......oodd',
        'oo........ohdd',
        'ho..........dh',
        'oh..........od',
        'oo..........hd',
        'ho..........do',
        'dho........ohd',
        '.dd........dd.',
      ]),
      back: t(-1, 9, [
        'oooooooooooooodd',
        'hoooooooooooooho',
        'oooooooooooooodd',
        'ohooooooooooodhd',
        'oooooooooooooodd',
        'dhooooooooooohdd',
        '.ddoooooooooddd.',
      ]),
    },
    up: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'ohhhhhhhoooodd',
        'ohhooooooooddd',
        'oooooooooooodd',
        'ohoooohooooodd',
        'oohooooohooodd',
        'ooohoooooohodd',
        'oohooooohooodd',
        'ohoooohooooddd',
        'oohoooooohoddd',
        'ooohoooohooddd',
        'dohooohooohodd',
        '.ddohooohoddd.',
        '...dddddddd...',
      ]),
    },
    side: {
      front: t(0, 2, [
        '....oooooo....',
        '..oohhhhhooo..',
        '.ohhHHhhhoood.',
        'oohhhhhhoooodd',
        'ohhooooooooodd',
        'oooooo.oooood.',
        'oo....oooooodd',
        '......ohoooodd',
        '......oohoohd.',
        '......ohooohdd',
        '.......oohoodd',
        '.......ohoohd.',
        '.......dohodd.',
        '........ddd...',
      ]),
    },
  },
};

/** Estilos cuja textura recebe pontilhado de cachos. */
export const TEXTURED: ReadonlySet<HairStyle> = new Set<HairStyle>(['curly', 'afro']);
