import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { dataDirectory } from "./ai";

export const PATH_STATUS = "/ponte/claude/status";
const NAME_SCRIPT = "status-claude-niko.mjs";
const VALIDITY_MS = 6 * 60 * 60_000;

export interface WindowStatus {
  id: "sessao" | "semanal";
  usado: number;
  reiniciaEm?: string;
}

let lastStatus: { em: number; janelas: WindowStatus[] } | null = null;

/** Send status data to Niko, then run the previous Claude Code status line with the same input. */
export const SCRIPT_STATUS = `// Generated by Niko. Remove through Niko (Code > Claude Code).
import { spawn } from "node:child_process";
import { existsSync } from "node:fs";

const [, , port, secret, marker] = process.argv;
const previous = marker?.startsWith("a=") ? marker.slice(2) : "";
let input = "";
for await (const chunk of process.stdin) input += chunk;

const request = fetch(\`http://127.0.0.1:\${port}${PATH_STATUS}\`, {
  method: "POST",
  headers: { "content-type": "application/json", "x-niko-gancho": secret },
  body: input,
  signal: AbortSignal.timeout(400),
}).catch(() => undefined);

function claudeShell() {
  const candidates = [process.env.CLAUDE_CODE_GIT_BASH_PATH, "C:\\\\Program Files\\\\Git\\\\bin\\\\bash.exe", "C:\\\\Program Files (x86)\\\\Git\\\\bin\\\\bash.exe"];
  return candidates.find((c) => c && existsSync(c));
}

if (previous) {
  let command = "";
  try {
    command = JSON.parse(Buffer.from(previous, "base64").toString("utf8")).command ?? "";
  } catch {
    command = "";
  }
  if (command) {
    const bash = claudeShell();
    const child = bash ? spawn(bash, ["-c", command], { stdio: ["pipe", "inherit", "ignore"] }) : spawn(command, { shell: true, stdio: ["pipe", "inherit", "ignore"] });
    const timeout = setTimeout(() => child.kill(), 5000);
    child.on("error", () => undefined);
    child.stdin.on("error", () => undefined);
    child.stdin.end(input);
    await new Promise((r) => child.on("close", r));
    clearTimeout(timeout);
  }
}
await request;
`;

export function pathScript() {
  return join(dataDirectory(), NAME_SCRIPT);
}

export function ensureScript() {
  const path = pathScript();
  if (existsSync(path) && readFileSync(path, "utf8") === SCRIPT_STATUS) return;
  mkdirSync(dataDirectory(), { recursive: true });
  writeFileSync(path, SCRIPT_STATUS, "utf8");
}

function hasBars(path: string) {
  return path.replace(/\\/g, "/");
}

export function isStatusNiko(value: unknown): boolean {
  const s = value as { command?: unknown } | null;
  return Boolean(s && typeof s === "object" && typeof s.command === "string" && s.command.includes(NAME_SCRIPT));
}

export function previousStatus(value: unknown): Record<string, unknown> | undefined {
  if (!isStatusNiko(value)) return value && typeof value === "object" ? (value as Record<string, unknown>) : undefined;
  const code = /\sa=([A-Za-z0-9+/=]+)\s*$/.exec(String((value as { command: string }).command))?.[1];
  if (!code) return undefined;
  try {
    const previous = JSON.parse(Buffer.from(code, "base64").toString("utf8")) as unknown;
    return previous && typeof previous === "object" && !Array.isArray(previous) ? (previous as Record<string, unknown>) : undefined;
  } catch {
    return undefined;
  }
}

export function statusNiko(previous: Record<string, unknown> | undefined, port: number, secret: string, node = process.execPath) {
  const guardada = previous && typeof previous.command === "string" && previous.command.trim() ? Buffer.from(JSON.stringify(previous), "utf8").toString("base64") : "";
  const command = `"${hasBars(node)}" "${hasBars(pathScript())}" ${port} ${secret}${guardada ? ` a=${guardada}` : ""}`;
  return { ...(previous ?? {}), type: "command", command: command };
}

function percentage(v: unknown): number | null {
  const n = typeof v === "number" ? v : NaN;
  return Number.isFinite(n) ? Math.max(0, Math.min(100, n)) : null;
}

export function readDataStatus(body: Record<string, unknown>): WindowStatus[] {
  const limits = (body.rate_limits ?? {}) as Record<string, { used_percentage?: unknown; resets_at?: unknown } | undefined>;
  const windows: WindowStatus[] = [];
  for (const [field, id] of [["five_hour", "sessao"], ["seven_day", "semanal"]] as const) {
    const item = limits[field];
    const used = percentage(item?.used_percentage);
    if (!item || used === null) continue;
    const restarts = typeof item.resets_at === "number" ? new Date(item.resets_at * 1000).toISOString() : undefined;
    windows.push({ id, usado: used, reiniciaEm: restarts });
  }
  return windows;
}

export function receiveStatus(body: Record<string, unknown>) {
  const windows = readDataStatus(body);
  if (windows.length) lastStatus = { em: Date.now(), janelas: windows };
}

export function usageFromStatus(now = Date.now()): WindowStatus[] | null {
  if (!lastStatus || now - lastStatus.em > VALIDITY_MS) return null;
  const vivas = lastStatus.janelas.filter((j) => !j.reiniciaEm || Date.parse(j.reiniciaEm) > now);
  return vivas.length ? vivas : null;
}
