import { lazy } from "react";
import {
  Home,
  MessageSquare,
  Building2,
  Plug,
  BookOpen,
  GraduationCap,
  Wallet,
  Target,
  CalendarDays,
  RefreshCw,
  Gauge,
  BrainCircuit,
  Trophy,
  Settings,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { Rota } from "../../tipos";

export const ICONE_ROTA: Record<Rota, LucideIcon> = {
  inicio: Home,
  chat: MessageSquare,
  escritorio: Building2,
  conexoes: Plug,
  journal: BookOpen,
  estudos: GraduationCap,
  financas: Wallet,
  metas: Target,
  calendario: CalendarDays,
  atualizacao: RefreshCw,
  ia: BrainCircuit,
  consumo: Gauge,
  conquistas: Trophy,
  configuracoes: Settings,
  agentes: Users,
};

export const PAGINA_ROTA: Record<Rota, React.LazyExoticComponent<() => React.JSX.Element>> = {
  inicio: lazy(() => import("../../modulos/inicio/Inicio")),
  chat: lazy(() => import("../../modulos/chat/Chat")),
  escritorio: lazy(() => import("../../modulos/escritorio/Escritorio")),
  conexoes: lazy(() => import("../../modulos/conexoes/Conexoes")),
  journal: lazy(() => import("../../modulos/journal/Journal")),
  estudos: lazy(() => import("../../modulos/estudos/Estudos")),
  financas: lazy(() => import("../../modulos/financas/Financas")),
  metas: lazy(() => import("../../modulos/metas/Metas")),
  calendario: lazy(() => import("../../modulos/calendario/Calendario")),
  atualizacao: lazy(() => import("../../modulos/atualizacao/Atualizacao")),
  ia: lazy(() => import("../../modulos/ia/ProvedoresIa")),
  consumo: lazy(() => import("../../modulos/consumo-ia/ConsumoIa")),
  conquistas: lazy(() => import("../../modulos/conquistas/Conquistas")),
  configuracoes: lazy(() => import("../../modulos/configuracoes/Configuracoes")),
  agentes: lazy(() => import("../../modulos/agentes/Agentes")),
};
